### ISSUE TITLE
Link system liblz4?

### ISSUE THREAD

**Issue by Berrysoft** [10XGenomics/lz4-rs#36]
How to link system liblz4?

**Comment by Fuuzetsu** [comment]
Presumably one has to add few lines to build.rs to add support for pkgconfig which is probably the easiest way forward.

**Comment by CathalMullan** [comment]
As a workaround, you can [override the build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts) to force linking:

```toml
[target.x86_64-unknown-linux-gnu.lz4]
rustc-link-lib = ["lz4"]
```
